= Spring Session - OGM Repositories
Eric Spiegelberg
:toc:

This guide describes how to use Spring Session backed by Neo4j's OGM.

NOTE: The completed guide can be found in the <<neo4-ogm-sample, sample application>>.

== Updating Dependencies
Before you use Spring Session, you must ensure to update your dependencies.
We assume you are working with a working Spring Boot web application.
If you are using Maven, ensure to add the following dependencies:

.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... -->

	<dependency>
		<groupId>org.springframework.session</groupId>
		<artifactId>spring-session</artifactId>
		<version>{spring-session-version}</version>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-data-neo4j</artifactId>
	</dependency>
</dependencies>
----

ifeval::["{version-snapshot}" == "true"]
Since We are using a SNAPSHOT version, we need to ensure to add the Spring Snapshot Maven Repository.
Ensure you have the following in your pom.xml:

.pom.xml
[source,xml]
----
<repositories>

	<!-- ... -->

	<repository>
		<id>spring-snapshot</id>
		<url>https://repo.spring.io/libs-snapshot</url>
	</repository>
</repositories>
----
endif::[]

ifeval::["{version-milestone}" == "true"]
Since We are using a Milestone version, we need to ensure to add the Spring Milestone Maven Repository.
Ensure you have the following in your pom.xml:

.pom.xml
[source,xml]
----
<repository>
	<id>spring-milestone</id>
	<url>https://repo.spring.io/libs-milestone</url>
</repository>
----
endif::[]

[[neo4j-ogm-spring-configuration]]
== Spring Configuration

After adding the required dependencies, we can create our Spring configuration.
The Spring configuration is responsible for creating a Servlet Filter that replaces the `HttpSession` implementation with an implementation backed by Spring Session.

// tag::config[]
All you have to do is to add the following Spring Configuration:

[source,java]
----
include::{samples-dir}/spring-session-data-neo4j-ogm-traditional-boot/src/main/java/org/springframework/session/neo4j/ogm/examples/config/HttpSessionConfig.java[tag=class]
----

<1> The `@EnableOgmHttpSession` annotation creates a Spring Bean with the name of `springSessionRepositoryFilter` that implements Filter.
The filter is what is in charge of replacing the `HttpSession` implementation to be backed by Spring Session.
In this instance Spring Session is backed by Neo4j's OGM.

<2> We explicitly configure `JdkOgmSessionConverter` since Spring Security's objects cannot be automatically persisted using Jackson (the default if Jackson is on the classpath).

// end::config[]

[[boot-ogm-configuration]]
== Configuring the OGM Connection

Spring Boot automatically creates a `SessionFactory` that connects Spring Session to a Neo4j instance on localhost on port 7474 (default port).
In a production environment you need to ensure to update your configuration to point to your Neo4j server.
For example, you can include the following in your *application.properties*

.src/main/resources/application.properties
----
spring.data.neo4j.uri=bolt://localhost:7687
spring.data.neo4j.username=neo4j
spring.data.neo4j.password=change-me
----

For more information, refer to http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-connecting-to-neo4j[Connecting to Neo4j] portion of the Spring Boot documentation.

[[boot-servlet-configuration]]
== Servlet Container Initialization

Our <<boot-spring-configuration,Spring Configuration>> created a Spring Bean named `springSessionRepositoryFilter` that implements `Filter`.
The `springSessionRepositoryFilter` bean is responsible for replacing the `HttpSession` with a custom implementation that is backed by Spring Session.

In order for our `Filter` to do its magic, Spring needs to load our `Config` class.
Last we need to ensure that our Servlet Container (i.e. Tomcat) uses our `springSessionRepositoryFilter` for every request.
Fortunately, Spring Boot takes care of both of these steps for us.

[[neo4j-ogm-sample]]
== OGM Sample Application

The OGM Sample Application demonstrates how to use Spring Session to transparently leverage Neo4j to back a web application's `HttpSession` when using Spring Boot.

[[neo4j-ogm-running]]
=== Running the OGM Sample Application

You can run the sample by obtaining the {download-url}[source code] and invoking the following command:

----
$ ./gradlew :samples:neo4j-ogm:bootRun
----

You should now be able to access the application at http://localhost:8080/

[[boot-explore]]
=== Exploring the security Sample Application

Try using the application. Enter the following to log in:

* **Username** _user_
* **Password** _password_

Now click the **Login** button.
You should now see a message indicating your are logged in with the user entered previously.
The user's information is stored in Neo4j rather than Tomcat's `HttpSession` implementation.

[[neo4j-ogm-how]]
=== How does it work?

Instead of using Tomcat's `HttpSession`, we are actually persisting the values in Neo4j.
Spring Session replaces the `HttpSession` with an implementation that is backed by OGM and Neo4j.
When Spring Security's `SecurityContextPersistenceFilter` saves the `SecurityContext` to the `HttpSession` it is then persisted into Neo4j.

When a new `HttpSession` is created, Spring Session creates a cookie named SESSION in your browser that contains the id of your session.
Go ahead and view the cookies (click for help with https://developer.chrome.com/devtools/docs/resources#cookies[Chrome] or https://getfirebug.com/wiki/index.php/Cookies_Panel#Cookies_List[Firefox]).

If you like, you can easily inspect the session using the Neo4j Browser. For example, open a browser and point to http://localhost:7474.

Alternatively, you can also delete the explicit key. Enter the following into the Neo4j Browser ensuring to replace `60f17293-839b-477c-bb92-07a9c3658843` with the value of your SESSION cookie:
----
match (n:SPRING_SESSION) where n.sessionId = '60f17293-839b-477c-bb92-07a9c3658843' delete n
----
Now visit the application at http://localhost:8080/ and observe that we are no longer authenticated.
